# Generated by Django 4.2 on 2023-04-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0031_braider_posted_pictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=81)),
                ('category', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='posted-pictures/')),
                ('braider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_media', to='main.braider')),
            ],
        ),
    ]
