# Generated by Django 4.2 on 2023-04-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedmedia',
            name='image',
            field=models.ImageField(upload_to='posted-pictures'),
        ),
    ]
