# Generated by Django 4.2 on 2023-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_postedmedia_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostedMedia',
        ),
    ]
