# Generated by Django 4.1.7 on 2023-04-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='braider',
            old_name='first_kugname',
            new_name='first_name',
        ),
    ]
