# Generated by Django 4.2 on 2023-04-16 14:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_kugname_braider_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braider',
            name='number',
        ),
        migrations.AddField(
            model_name='braider',
            name='city',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='braider',
            name='country',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='braider',
            name='insta_id',
            field=models.CharField(default='braidstarz', max_length=40),
        ),
        migrations.AddField(
            model_name='braider',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='No Number.', max_length=128, region=None),
        ),
    ]
