# Generated by Django 4.2 on 2023-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_braider_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braider',
            name='city',
        ),
        migrations.AddField(
            model_name='braider',
            name='cityd',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
