# Generated by Django 4.2 on 2023-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_braider_cityd_braider_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='user_type',
            field=models.CharField(choices=[('Braider', 'braider'), ('Customer', 'customer')], default='Customer', max_length=8),
        ),
    ]
