# Generated by Django 4.2 on 2023-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_braider_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='user_type',
            field=models.CharField(choices=[('braider', 'customer')], default='customer', max_length=8),
        ),
    ]
