# Generated by Django 4.2 on 2023-04-19 22:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_braider_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120, validators=[main.models.validate_password]),
        ),
        migrations.AlterField(
            model_name='braider',
            name='user_type',
            field=models.CharField(choices=[('c', 'braider'), ('b', 'customer')], default='customer', max_length=8),
        ),
    ]
