# Generated by Django 4.2 on 2023-04-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_braider_password_alter_braider_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='braider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
