# Generated by Django 4.2 on 2023-04-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_braider_email_alter_braider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
