# Generated by Django 4.2 on 2023-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_braider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
