# Generated by Django 4.2 on 2023-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_braider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
