# Generated by Django 4.2 on 2023-04-20 01:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_braider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='insta_id',
            field=models.CharField(default='braidstarz', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='No Number.', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='user_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
