# Generated by Django 4.2 on 2023-04-20 01:49

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_braider_email_alter_braider_insta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120, validators=[main.models.validate_password]),
        ),
    ]
