# Generated by Django 4.2 on 2023-04-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_braider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
