# Generated by Django 4.2 on 2023-04-20 02:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_braider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braider',
            name='country',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120, validators=[main.models.validate_password]),
        ),
    ]
