# Generated by Django 4.2 on 2023-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_braider_country_alter_braider_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='braider',
            name='user_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
