# Generated by Django 4.2 on 2023-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_braider_last_login_alter_braider_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
