# Generated by Django 4.2 on 2023-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_braider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
