# Generated by Django 4.2 on 2023-04-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_braider_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
