# Generated by Django 4.2 on 2023-04-23 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_braider_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braider',
            name='city',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='country',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='insta_id',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='braider',
            name='website',
        ),
        migrations.AlterField(
            model_name='braider',
            name='email',
            field=models.EmailField(max_length=252, unique=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='password',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='braider',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='No Number.', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='braider',
            name='user_name',
            field=models.CharField(max_length=27, unique=True),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 4, 24, 20, 44, 9, 396846))),
                ('is_valid', models.BooleanField(default=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(default='braidstarz', max_length=30, unique=True)),
                ('twitter', models.CharField(default='braidstarz', max_length=15, unique=True)),
                ('youtube', models.CharField(default='braidstarz', max_length=20, unique=True)),
                ('tiktok', models.CharField(default='braidstarz', max_length=24, unique=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider')),
            ],
        ),
        migrations.CreateModel(
            name='PublicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=23)),
                ('last_name', models.CharField(max_length=22)),
                ('user_type', models.CharField(choices=[('c', 'braider'), ('b', 'customer')], default='customer', max_length=8)),
                ('biography', models.CharField(max_length=1024)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider')),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='none', max_length=27)),
                ('city', models.CharField(default='none', max_length=81)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('address', models.CharField(max_length=252)),
                ('website', models.URLField(null=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider')),
            ],
        ),
    ]
