# Generated by Django 4.2 on 2023-04-23 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_verification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 5, 31, 372768)),
        ),
    ]
