# Generated by Django 4.2 on 2023-04-24 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_businessinfo_address_alter_businessinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='insta',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, error_messages={'unique': 'Instagram ID already exists.'}, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='biography',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 11, 8, 59, 627414)),
        ),
    ]
