# Generated by Django 4.2 on 2023-04-26 16:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_socialmedia_insta_socialmedia_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='posted_pictures',
            field=models.ImageField(null=True, upload_to='posted-pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(512000)]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 21, 5, 16, 633304)),
        ),
    ]
