# Generated by Django 4.2 on 2023-04-26 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_braider_posted_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 21, 14, 41, 452798)),
        ),
    ]
