# Generated by Django 4.2 on 2023-04-28 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_braider_posted_pictures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='braider',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 21, 2, 25, 610400)),
        ),
    ]
