# Generated by Django 4.2 on 2023-04-30 01:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_braider_show_email_braider_show_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='website',
            field=models.URLField(max_length=234, null=True),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
        migrations.AlterField(
            model_name='post',
            name='braider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.braider'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='biography',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(error_messages={'unique': 'Facebook ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(error_messages={'unique': 'Instagram ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(error_messages={'unique': 'Tiktok ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(error_messages={'unique': 'Twitter ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(error_messages={'unique': 'Youtube ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 6, 11, 34, 115897)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
    ]
