# Generated by Django 4.2 on 2023-04-30 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_businessinfo_name_alter_businessinfo_rel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(error_messages={'blank': 'fuck'}, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='biography',
            field=models.CharField(blank=True, error_messages={'blank': 'are you serious?'}, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, error_messages={'unique': 'Facebook ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, error_messages={'unique': 'Instagram ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, error_messages={'unique': 'Tiktok ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, error_messages={'unique': 'Twitter ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(blank=True, error_messages={'unique': 'Youtube ID already exists.'}, max_length=234, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 7, 25, 8, 389216)),
        ),
    ]
