# Generated by Django 4.2 on 2023-04-30 03:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_post_image_alter_publicinfo_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 7, 39, 31, 148506)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.braider'),
        ),
    ]
