# Generated by Django 4.2 on 2023-05-01 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_verification_expires_at_alter_verification_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(blank=True, max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='website',
            field=models.URLField(blank=True, max_length=234, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 18, 38, 15, 778827)),
        ),
    ]
