# Generated by Django 4.2 on 2023-05-02 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_businessinfo_address_alter_businessinfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicinfo',
            name='profile_picture',
            field=models.ImageField(default='profile_pic.jpg', null=True, upload_to='profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(error_messages={'blank': 'Image Cannot Blank!'}, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 6, 25, 696385)),
        ),
    ]
