# Generated by Django 4.2 on 2023-05-02 13:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_publicinfo_profile_picture_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='braider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.braider'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(error_messages={'blank': 'You Cannot Post A Picture Without The Picture Itself. Right?'}, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic.jpg', null=True, upload_to='profile-pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(512000)]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 17, 38, 30, 250825)),
        ),
    ]
