# Generated by Django 4.2 on 2024-02-23 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_customerverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 15, 3, 1, 750611)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 15, 3, 1, 749612)),
        ),
    ]
