# Generated by Django 4.2 on 2024-02-23 13:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_braider_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 17, 19, 23, 952786)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 17, 19, 23, 951787)),
        ),
    ]
