# Generated by Django 4.2 on 2024-02-23 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_customer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(blank=True, default='Not Specified', max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(blank=True, default='Not Specified', max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='customerverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 15, 29, 312038)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 15, 29, 312038)),
        ),
    ]
